---
  - name: install nginx
    apt: name=nginx state=present

  - name: remove default site
    file: path=/etc/nginx/sites-enabled/default state=absent

  - name: does nginx-site already exist
    stat: path=/etc/nginx/sites-available/{{project}}
    register: site

  - name: create site
    template: src=nginx_template_http_only.j2 dest=/etc/nginx/sites-available/{{project}}
    when: site.stat.exists == False

  # enable the file by linking it to the sites-enabled directory
  - name: create symlink
    file: src=/etc/nginx/sites-available/{{project}}  dest=/etc/nginx/sites-enabled/{{project}} state=link

  - name: restart nginx
    service: name=nginx state=restarted

  # open up firewall to normal traffic on port 80
  - name: Allow everything and enable UFW
    ufw:
      state: enabled
      policy: allow