---
# file: roles/common/tasks/main.yml 
  - name: update packages
    apt: update_cache=yes

  - name: install python3 packages
    apt: 
      name: ['python3', 'python3-dev', 'python3-pip']
      update_cache: yes 
      state: present
    tags: packages

  - name: install virtualenv
    apt:
      name: python-virtualenv 
      state: present

  # TODO
  # - name: install rabbitmq-server
  #   apt: name=rabbitmq-server state=present

  # - name: add secure rabbitmq-server conf
  #   copy: src=rabbitmq-env.conf dest=/etc/rabbitmq/rabbitmq-env.conf

  # - name: restart rabbitmq-server
  #   service: name=rabbitmq-server state=restarted
  #   become: true

  - name: add gunicorn systemd service
    template: >
      src=gunicorn_systemd_template.j2
      dest=/etc/systemd/system/gunicorn.service
  - name: reload systemd conf
    command: systemctl daemon-reload
