---
  - name: Install prerequisites
    apt: 
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'gnupg2']
      update_cache: yes
      state: present

  - name: Add Docker GPG key
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

  - name: update packages
    apt: 
      update_cache: yes

  - name: install python3
    apt: 
      name: ['python3', 'python3-dev', 'python3-pip', 'python-setuptools', 'virtualenv', 'python-pip']
      state: present

  - name: install docker with pip
    pip:
      name: docker

  # - name: install Docker
  #   apt: 
  #     name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
  #     state: present

  - name: install jenkins/blueocean
    docker_container:
      name: jenkins_container
      image: jenkinsci/blueocean
      ports:
        - "8081:8081"
      volumes:
        - "jenkins-data:/var/jenkins_home"
        - "/var/<run/docker.sock:/var/run/docker.sock"

  # - name: Forward port 80 to 8080
  #   iptables:
  #     table: nat
  #     chain: PREROUTING
  #     protocol: tcp
  #     match: tcp
  #     destination_port: "80"
  #     jump: REDIRECT
  #     to_ports: "8080"
  #     comment: Redirect web traffic to port 8080
  
  - name: wait for port
    wait_for:
      port: 8081

  - name: Get Admin Password
    shell: cat /var/lib/docker/volumes/jenkins-data/_data/secrets/initialAdminPassword
    register: initialAdminPassword

  - name: display initialAdminPassword in Ansible shell
    debug: 
      msg: "{{initialAdminPassword.stdout}}"
